version: '3'
services:
  backend:
    build: .
    restart: always
    expose:
      - "80"
      - "443"
    env_file:
      - environment.txt
    volumes:
      - ./docker_data:/root/Destiny2Manifest
    networks:
      - my-network
  nginx:
    depends_on:
      - backend
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - my-network
networks:
  my-network: